### ISSUE TITLE
Thermostat is not working

### ISSUE THREAD

**Issue by DewGew** [DewGew/Domoticz-Google-Assistant#32]
Cant find whats wrong with this..
def excute is not running when changing setpoint.

**Comment by DewGew** [comment]
Thermostat is working now for me. Others have issues? Try Re-link your integration to the Google Assistant or restart your test in actions on google / deploy / account linking  click on 'Test'

**Comment by d-EScape** [comment]
Unfortunately that didn’t solve it for me. I tried both, re-link and restart test. After digging around and trying several print statements to see which part of the code is run I could not narrow it down. However I never saw the execute method being called. Not the one in trait.py and not even the one in the _GoogleEntity class. I suspect the root cause is not in the execution code, but during the registration of the device with actions on google. Google just does not seem to ‘know’ that the thermostat can be set (not just read). I could be wrong of course :$

**Comment by DewGew** [comment]
> Unfortunately that didn’t solve it for me. I tried both, re-link and restart test. After digging around and trying several print statements to see which part of the code is run I could not narrow it down. However I never saw the execute method being called. Not the one in trait.py and not even the one in the _GoogleEntity class. I suspect the root cause is not in the execution code, but during the registration of the device with actions on google. Google just does not seem to ‘know’ that the thermostat can be set (not just read). I could be wrong of course :$

Try latest I think I fixed it

**Comment by d-EScape** [comment]
You did! Just tried it and i can now set the temperature :-D
