### ISSUE TITLE
Sync will not delete removed devices

### ISSUE THREAD

**Issue by Jochem22** [DewGew/Domoticz-Google-Assistant#67]
When i look at my DZGA devices page there are devices listed that are already deleted from my domoticz system. When i sync they wont get deleted. Google Home now has devices that are not existing anymore. The devices that should be removed dont show up at json.htm?type=devices either. Only way to fix this is to restart DZGA.

**Comment by DewGew** [comment]
Devices are a stored arrays, when doing a sync I dont think dzga dump any devices, just updates those that have changed or have been added. Need find out how to fix this.

**Comment by DewGew** [comment]
You can also On your mobile device, open the Google Home app.
On the Home tab, tap the “Add” quick action .
Tap Set up a device
Tap Have something already set up?
Select your device app e.g: "[test]Your Appname"
Tap Search for new devices.

**Comment by RonandoDeLaVega** [comment]
Hello DewGew,

First of all, thanks for your awesome work and your quick answers on all the opened issues !!

I've noticed the same problem : when a device is deleted ; it's still persistent in DZGA and persistent in Google Home.

I think the issue comes from the sync between DZGA and Domoticz (as it still appears in Device tab in DZGA).

Thanks again,
Ronando

**Comment by DewGew** [comment]
Try latest beta
